// <auto-generated />
using System;
using GameOfDrones.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameOfDrones.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("GameOfDrones.Api.Models.GameRoom", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("P1Wins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("P2Wins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PendingP1Move")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingP2Move")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Player1Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Player2Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedLabel")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedP1Move")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedP2Move")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResolvedRoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WantsRematchP1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WantsRematchP2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WinnerName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GameRooms");
                });

            modelBuilder.Entity("GameOfDrones.Api.Models.KillRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefeatedMoveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KillerMoveId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DefeatedMoveId");

                    b.HasIndex("KillerMoveId", "DefeatedMoveId")
                        .IsUnique();

                    b.ToTable("KillRules");
                });

            modelBuilder.Entity("GameOfDrones.Api.Models.Move", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("GameOfDrones.Api.Models.PlayerStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("GamesWon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("PlayerStats");
                });

            modelBuilder.Entity("GameOfDrones.Api.Models.KillRule", b =>
                {
                    b.HasOne("GameOfDrones.Api.Models.Move", "DefeatedMove")
                        .WithMany()
                        .HasForeignKey("DefeatedMoveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameOfDrones.Api.Models.Move", "KillerMove")
                        .WithMany("RulesWhereKiller")
                        .HasForeignKey("KillerMoveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefeatedMove");

                    b.Navigation("KillerMove");
                });

            modelBuilder.Entity("GameOfDrones.Api.Models.Move", b =>
                {
                    b.Navigation("RulesWhereKiller");
                });
#pragma warning restore 612, 618
        }
    }
}
